// Tutorial lesson content — the prose each `crtr dev tutorial <track>` step
// serves back to the agent running the tutorial.
//
// These bodies address the AGENT, not the user: the agent is the teacher and
// the command is a prompt server. A lesson says what to inspect on this
// machine, what to explain, and what to OFFER to change — it never edits
// anything itself. Config the tutorial writes (tmux, terminal keys) is written
// by the agent after showing the user a diff and getting a yes, so approval
// happens in the conversation where the change is visible.

const BASIC = [
  {
    title: 'Terminal Option key — do this first',
    body: [
      'Every crouter global is an Alt chord, and on macOS terminals Option defaults to emitting accented characters. Until this is fixed, `Alt+C` types `ç` and the user concludes crouter is broken. Fix it before teaching anything else.',
      '',
      'Read `TERM_PROGRAM` to identify the terminal, then give the exact path:',
      '',
      '- **iTerm2** — Settings → Profiles → Keys → General → set **Left option** and **Right option** to `Esc+`.',
      '- **Ghostty** — `macos-option-as-alt = true` in `~/.config/ghostty/config`.',
      '- **kitty** — `macos_option_as_alt yes` in `~/.config/kitty/kitty.conf`.',
      '- **WezTerm** — `send_composed_key_when_left_alt_is_pressed = false`.',
      '- **Alacritty** — `window.option_as_alt = "Both"`.',
      '- **Terminal.app** — Settings → Profiles → Keyboard → check "Use Option as Meta key".',
      '',
      'For the file-based terminals, offer to make the edit yourself: show the exact line you would add, wait for a yes, then write it and tell them to reload. iTerm2 and Terminal.app are GUI-only, so walk them through it.',
      '',
      '**Verify interactively before moving on.** Ask the user to press `Alt+C` and tell you what happened. A menu means it works. A `ç`, or nothing, means the setting did not take — a GUI terminal usually needs a new window, and inside tmux it needs the terminal restarted. Do not advance until they confirm the menu opened; every remaining lesson depends on it.',
    ].join('\n'),
  },
  {
    title: 'tmux — meet the user where they are',
    body: [
      'crouter runs its viewers as tmux panes, so a user who cannot split, close, and move between panes cannot drive it. Teach the four verbs that matter: **new pane**, **new window**, **close pane**, **next pane / next window**.',
      '',
      'Adapt to what is already there. Check for `~/.tmux.conf` and `~/.config/tmux/tmux.conf`, and run `tmux show-options -g prefix` if a server is up.',
      '',
      '- **No config at all** — offer the starter config below wholesale.',
      '- **An existing config** — read it first. Teach in *their* prefix and *their* bindings, and only offer to fill genuine gaps. Someone who already bound `|` and `-` for splits does not want your opinion; they want to know how their muscle memory maps onto crouter.',
      '',
      'The starter config, for a user who has nothing:',
      '',
      '```tmux',
      '# prefix on Ctrl-a — easier to reach than the default Ctrl-b',
      'set -g prefix C-a',
      'unbind C-b',
      'bind C-a send-prefix',
      '',
      '# splits that look like what they do, opening in the current directory',
      'bind | split-window -h -c "#{pane_current_path}"',
      'bind - split-window -v -c "#{pane_current_path}"',
      'bind c new-window -c "#{pane_current_path}"',
      '',
      '# move between panes without the prefix',
      'bind -n M-Left  select-pane -L',
      'bind -n M-Right select-pane -R',
      'bind -n M-Up    select-pane -U',
      'bind -n M-Down  select-pane -D',
      '',
      '# sane defaults',
      'set -g mouse on',
      'set -g base-index 1',
      'setw -g pane-base-index 1',
      'set -g escape-time 0',
      'set -g history-limit 50000',
      '```',
      '',
      '**Never write this silently.** Show the user exactly what you propose to add, as a diff against what is already in the file, and wait for an explicit yes. If they have a config, back it up first and say where the backup went. After writing, tell them to run `tmux source-file <path>` or start a fresh session.',
      '',
      'One caveat worth stating out loud: `escape-time 0` matters for crouter specifically, because a nonzero value makes tmux wait after every Escape and Alt chord, which shows up as the Alt+C menu feeling laggy or dropping keys.',
    ].join('\n'),
  },
  {
    title: 'The crouter menu — Alt+C',
    body: [
      'Teach `Alt+C` as **the** crouter prefix. It opens an action menu, and nearly everything is `Alt+C` then one key. Frame it as a menu the user opens and reads, not a table to memorize — the menu shows its own options, so the only thing they truly have to remember is `Alt+C`.',
      '',
      'Have them press `Alt+C` now and read the menu aloud to you. Then walk the entries that matter early:',
      '',
      '| Chord | What it does |',
      '|---|---|',
      '| `Alt+C` `/` | **Find node** — the canvas navigator |',
      '| `Alt+C` `g` | **Canvas graph** |',
      '| `Alt+C` `i` | **Inspect** the focused node |',
      '| `Alt+C` `s` | Generate a **recap** — goal and state, plus a refreshed title |',
      '| `Alt+C` `,` | **Settings** |',
      '| `Alt+C` `x` | **Close** this node and its subtree |',
      '',
      'Two globals skip the menu entirely, because they are used constantly:',
      '',
      '| Chord | What it does |',
      '|---|---|',
      '| `Alt+I` | Toggle the human **inbox** |',
      '| `Alt+]` / `Alt+[` | Next / previous node |',
      '',
      'Mention that `Alt+C` `,` is where every one of these bindings can be rebound, so nothing you just taught is a permanent constraint. Do not walk the settings panel now; just plant that it exists.',
    ].join('\n'),
  },
  {
    title: 'Resuming a conversation',
    body: [
      '`Alt+C` then `/` opens the canvas navigator: a searchable list of every conversation on this machine. Pick one, land in it, keep going.',
      '',
      'Have the user open it and look around. On a fresh install there may be only one entry — that is fine, the point is the reflex, not the contents.',
      '',
      'The idea to land, which matters more than the keystroke: **conversations are durable and addressable.** A crouter conversation is not a terminal session that dies when the window closes. It is a node on the canvas with an id, a saved transcript, and a context directory. Walking away does not lose it, and finding it again is a search rather than an act of archaeology.',
      '',
      'Worth mentioning while they are in the navigator: `p` pins a conversation so it sorts to the top, which is how people keep their two or three live threads reachable without searching.',
    ].join('\n'),
  },
  {
    title: 'Memory',
    body: [
      'Keep this abstract. The user does not need the storage model; they need to know memory exists, that it is scoped, and that they can drive it by just asking.',
      '',
      'Cover four points:',
      '',
      '1. **Two kinds.** *Knowledge* is how to do something — a playbook, a technique, a fact about a system. *Preference* is how the user wants the agent to behave — a standing instruction or a correction.',
      '',
      '2. **Where a document lives decides who sees it.** A memory can be scoped to everything the user does, to one project, to one profile, or to a single node. That scope choice is what keeps a work convention from leaking into a personal project.',
      '',
      '3. **Documents are routed, not loaded.** Each one carries a condition describing when it is worth reading. An agent pulls in the handful that match the task instead of loading everything, which is why a large memory store does not slow anything down or crowd out the actual work.',
      '',
      '4. **The practical instruction is one sentence: just say "remember that."** The agent decides the kind, writes the document, and picks the scope. The user can correct any of those in follow-up. This is most of what a new user needs; the rest is detail they can pick up when they care.',
      '',
      'If you have genuinely learned something durable about this user during the tutorial — their terminal, their tmux prefix, a convention they stated — offer to save it now as a real demonstration. A memory the user watched get created from a real fact beats any explanation of the feature.',
    ].join('\n'),
  },
  {
    title: 'The graph — Alt+C then g',
    body: [
      'The graph shows the node tree: who spawned whom, what is running, what has finished.',
      '',
      'A tour against a single row teaches nothing, so put a few nodes on the canvas first:',
      '',
      '```bash',
      'crtr dev tutorial scenario start idle-nodes',
      '```',
      '',
      'That creates three idle nodes purely for the demo. They never run a turn, so it costs nothing. Then have the user press `Alt+C` `g` and navigate:',
      '',
      '| Key | Action |',
      '|---|---|',
      '| `j` / `k` | Move down / up |',
      '| `Enter` | Focus the selected node — open it in this pane |',
      '| `l` / `h` | Move to a child / back to the manager |',
      '| `m` | Jump to the selected node’s manager |',
      '| `r` | Revive a dormant node |',
      '| `x` | Close the selected subtree |',
      '| `Esc` | Dismiss the graph |',
      '',
      '**Be honest about what the demo shows.** The scenario creates independent roots, not a tree, so `j`/`k`/`Enter`/`Esc` are the keys they can actually practice here. Explain `h` and `l` as what they will use once they delegate work and have real parent-child structure — the advanced track covers where that structure comes from.',
      '',
      'Then tear the demo down:',
      '',
      '```bash',
      'crtr dev tutorial scenario clean idle-nodes',
      '```',
      '',
      '**Say this part explicitly — it changes how people use crouter.** The viewer and the node are decoupled. Closing the tmux pane, closing the window, or quitting the terminal outright detaches the viewer and leaves the node running. Nothing is killed by walking away, and reattaching later picks up exactly where it was. New users assume the opposite and babysit panes they do not need to; tell them plainly that they can close it. Ending a node is a deliberate, separate action (`Alt+C` `x`).',
    ].join('\n'),
  },
  {
    title: 'The inbox — Alt+I',
    body: [
      'The inbox is how a node reaches the user. When an agent needs a decision, wants a document reviewed, or is blocked on something only a person can settle, it posts there and goes dormant. Without the inbox that agent looks stuck; with it, the user can see it is simply waiting on them.',
      '',
      'Give them something real to answer:',
      '',
      '```bash',
      'crtr dev tutorial scenario start pending-ask',
      '```',
      '',
      'Then have them press `Alt+I`, read the pending item, and respond to it. Walk them through selecting the item and answering, and point out that a real answer wakes the waiting node immediately — a reply is not filed for later, it resumes the work that was blocked on it. (This demo request has no node behind it, so nothing wakes; say so rather than implying otherwise.)',
      '',
      'Clean up when the point has landed:',
      '',
      '```bash',
      'crtr dev tutorial scenario clean pending-ask',
      '```',
      '',
      'The habit worth leaving them with: **check the inbox when something seems idle.** An agent that appears to have stopped has very often asked a question and is waiting.',
      '',
      'This is the last basic lesson. Close by telling them the advanced track exists — `crtr dev tutorial advanced`, covering promotion and node lifecycles — and that it is worth running once they have done real work and want to understand what crouter is doing underneath.',
    ].join('\n'),
  },
];

const ADVANCED = [
  {
    title: 'Promotion to orchestrator',
    body: [
      'Every node is one of two modes. A **base node** does the work itself — reads, edits, runs commands. An **orchestrator** holds a roadmap and delegates, spawning children for the pieces and integrating what comes back.',
      '',
      '- `Alt+C` `o` promotes the focused node to orchestrator.',
      '- `Alt+C` `Shift+O` demotes it back to a base node.',
      '- From inside a conversation, `/promote` does the same thing, and `/promote <kind>` specializes it at the same time.',
      '',
      'Teach *when*, because the keystroke is the easy part. Promotion earns its cost when the work has **genuinely independent parts** that can run at the same time, or **many large phases** that would otherwise fill a single context window. It is the wrong move for a two-file change: spinning up a child and waiting for its report costs more than doing the work directly.',
      '',
      'The mechanism worth naming: a child reports up to whoever subscribes to it, and that report **wakes the manager**. Nobody polls. An orchestrator delegates, ends its turn, and comes back when there is something to integrate — which is why a fan-out of five children costs one manager context window rather than five.',
      '',
      'The failure mode to warn about is recursive delegation: an orchestrator that hands its entire assignment to one child has not decomposed anything, it has added a layer. Each child needs a bounded outcome genuinely smaller than the whole.',
    ].join('\n'),
  },
  {
    title: 'Terminal and resident nodes',
    body: [
      'Lifecycle is the other axis, orthogonal to mode. It answers: what does this node owe, and when is it allowed to end?',
      '',
      '- A **terminal** node owes a final report up the spine. It does its work, delivers, and reaps itself. This is the shape for bounded delegated work.',
      '- A **resident** node is interactable, never forced to submit a final, and stays wakeable indefinitely. This is the shape for a conversation with a person.',
      '',
      '`Alt+C` `d` demotes a node to terminal. `Alt+C` `Shift+R` makes one resident. Roots default to resident; managed children default to terminal.',
      '',
      '**Why it works this way** — this is the part worth understanding, not memorizing.',
      '',
      'A terminal node is *depended upon to finish*. Its manager subscribed to it and will be woken by its report, so the guarantee that it must eventually deliver one is exactly what makes delegation safe. Without it, an orchestrator could wait forever on a child that quietly decided it was done.',
      '',
      'A resident node must never be forced to close mid-sentence. A conversation with a person has no natural completion — the user may come back tomorrow — so requiring a final report would either truncate the conversation or produce a meaningless one. Residency removes that requirement, and going dormant costs nothing: the node holds no window and burns no compute while it waits.',
      '',
      'This is why **the user\'s own conversation is resident and cannot be finished on its behalf**, while the children it spawns are terminal and reap themselves when they report. The user sees this as agents that clean up after themselves while their own thread persists — that is the lifecycle axis doing its job.',
      '',
      'Related and worth a mention: a **yield** lets a resident node whose context is filling revive fresh under the same identity and mandate, carrying a note to its future self. The conversation survives; only the context window is recycled.',
    ].join('\n'),
  },
];

const TRACKS = { basic: BASIC, advanced: ADVANCED };

export function lessonsFor(track) {
  return TRACKS[track];
}

export function tableOfContents(track) {
  return lessonsFor(track)
    .map((l, i) => `${i + 1}. ${l.title}`)
    .join('\n');
}
